language: elixir
cache:
  directories:
  - deps
  - _build/test
elixir:
  - 1.5.2
otp_release:
  - 20.0
env:
  global:
    - MIX_ENV=test
script:
  # Install dependencies
  - "mix deps.get"
  # Run all tests except pending ones
  - "mix test --exclude pending --trace"
  # Run static code analysis
  - "mix credo"
  # Check code style
  - "mix dogma"
  # Check type safety
  - "mix dialyzer --unmatched_returns --error_handling --race_conditions --underspecs"
after_script:
  # Submit docs coverage to Inch CI
  - "mix inch.report"
  # Submit code coverage report to Coveralls
  - "mix coveralls.travis"
