language: elixir
cache:
  directories:
  - deps
  - _build/dev
  - _build/test
elixir:
  - 1.5.0
otp_release:
  - 20.0
env:
  global:
    - MIX_ENV=test
script:
  # Install dependencies
  - "mix deps.get"
  # Run all tests except pending ones
  - "mix test --exclude pending --trace"
  # # Run static code analysis
  # - "mix credo"
  # # Check code style
  # - "mix dogma"
  # Check type safety
  - "MIX_ENV=dev mix dialyzer --unmatched_returns --error_handling --race_conditions --underspecs"
after_script:
  # Submit docs coverage to Inch CI
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
  # Submit code coverage report to Coveralls
  - "mix coveralls.travis"
